"""
Horus Comment Handlers
=====================

Event handlers and interaction logic for comments and replies.
"""

from horus.utils.globals import comments_dock
from horus.comments.comment_widgets import create_comment_widget


def on_add_comment():
    """Handle adding a general comment."""
    global comments_dock

    try:
        comments_widget = comments_dock.widget() if comments_dock else None
        if not comments_widget:
            return

        comment_text = comments_widget.comment_text.toPlainText().strip()
        if not comment_text:
            return

        # Create new comment data
        new_comment = {
            "id": 999,  # Would be generated by database
            "user": "Current User",
            "avatar": "CU",
            "time": "Just now",
            "frame": None,
            "text": comment_text,
            "likes": 0,
            "replies": []
        }

        # Create and add comment widget
        comment_widget = create_comment_widget(new_comment)
        comments_widget.comments_container.layout().insertWidget(
            comments_widget.comments_container.layout().count() - 1, comment_widget)

        comments_widget.comment_text.clear()

        print(f"Added general comment: {comment_text}")

    except Exception as e:
        print(f"Error adding comment: {e}")


def on_add_frame_comment():
    """Handle adding a frame-specific comment."""
    global comments_dock

    try:
        comments_widget = comments_dock.widget() if comments_dock else None
        if not comments_widget:
            return

        comment_text = comments_widget.comment_text.toPlainText().strip()
        if not comment_text:
            return

        # Get current frame from Open RV
        from horus.comments.annotations import get_current_frame
        current_frame = get_current_frame()

        # Create new frame-specific comment data
        new_comment = {
            "id": 998,  # Would be generated by database
            "user": "Current User",
            "avatar": "CU",
            "time": "Just now",
            "frame": current_frame,
            "text": comment_text,
            "likes": 0,
            "priority": "Medium",
            "status": "Open",
            "replies": []
        }

        # Create and add comment widget
        comment_widget = create_comment_widget(new_comment)
        comments_widget.comments_container.layout().insertWidget(
            comments_widget.comments_container.layout().count() - 1, comment_widget)

        comments_widget.comment_text.clear()

        print(f"Added frame comment for frame {current_frame}: {comment_text}")

    except Exception as e:
        print(f"Error adding frame comment: {e}")


def show_reply_input(comment_id):
    """Show the reply input for a specific comment."""
    global comments_dock

    try:
        comments_widget = comments_dock.widget() if comments_dock else None
        if not comments_widget:
            return

        # Find and show the reply input frame
        reply_input_frame = comments_widget.findChild(
            comments_widget.__class__.__bases__[0], f"reply_input_{comment_id}")
        if reply_input_frame:
            reply_input_frame.setVisible(True)
            # Focus on the text input
            reply_text = comments_widget.findChild(
                comments_widget.__class__.__bases__[0], f"reply_text_{comment_id}")
            if reply_text:
                reply_text.setFocus()

    except Exception as e:
        print(f"Error showing reply input: {e}")


def hide_reply_input(comment_id):
    """Hide the reply input for a specific comment."""
    global comments_dock

    try:
        comments_widget = comments_dock.widget() if comments_dock else None
        if not comments_widget:
            return

        # Find and hide the reply input frame
        reply_input_frame = comments_widget.findChild(
            comments_widget.__class__.__bases__[0], f"reply_input_{comment_id}")
        if reply_input_frame:
            reply_input_frame.setVisible(False)
            # Clear the text
            reply_text = comments_widget.findChild(
                comments_widget.__class__.__bases__[0], f"reply_text_{comment_id}")
            if reply_text:
                reply_text.clear()

    except Exception as e:
        print(f"Error hiding reply input: {e}")


def post_reply(comment_id):
    """Post a reply to a specific comment."""
    global comments_dock

    try:
        comments_widget = comments_dock.widget() if comments_dock else None
        if not comments_widget:
            return

        # Get reply text
        reply_text_widget = comments_widget.findChild(
            comments_widget.__class__.__bases__[0], f"reply_text_{comment_id}")
        if not reply_text_widget:
            return

        reply_text = reply_text_widget.toPlainText().strip()
        if not reply_text:
            return

        # Create new reply data
        new_reply = {
            "id": 997,  # Would be generated by database
            "user": "Current User",
            "avatar": "CU",
            "time": "Just now",
            "text": reply_text,
            "likes": 0
        }

        # Find replies container and add new reply
        replies_container = comments_widget.findChild(
            comments_widget.__class__.__bases__[0], f"replies_{comment_id}")
        if replies_container:
            from horus.comments.comment_widgets import create_reply_widget
            reply_widget = create_reply_widget(new_reply)
            replies_container.layout().addWidget(reply_widget)

        # Hide reply input
        hide_reply_input(comment_id)

        print(f"Posted reply to comment {comment_id}: {reply_text}")

    except Exception as e:
        print(f"Error posting reply: {e}")


def on_open_annotations_popup():
    """Open the annotations popup window."""
    from horus.utils.globals import annotations_popup_window
    from horus.comments.annotations import create_annotations_popup

    try:
        global annotations_popup_window
        
        if annotations_popup_window is None:
            annotations_popup_window = create_annotations_popup()
        
        if annotations_popup_window:
            annotations_popup_window.show()
            annotations_popup_window.raise_()
            annotations_popup_window.activateWindow()
            print("Opened annotations popup")
        else:
            print("Failed to create annotations popup")
            
    except Exception as e:
        print(f"Error opening annotations popup: {e}")
